prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>  
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>

SELECT DISTINCT ?obj ?museum ?text ?img ?deeplink  ?place_uri ?place_country_code ?time_uri ?time_label ?technique_group ?material_group ?depict_group ?type_a_group
WHERE {
  GRAPH ?museum {
     ?dig a crmdig:D1_Digital_Object . }
  
      ?dig ecrm:P129_is_about ?prod .
      ?prod ecrm:P108_has_produced ?obj .
      ?obj a ecrm:E22_Man-Made_Object .

      optional {?obj rdfs:comment ?text }

      optional {?obj ecrm:P138i_has_representation ?img .
      ?img schema:contentUrl ?deeplink. FILTER contains(str(?deeplink), "silknow")}
      

     optional{ ?prod ecrm:P8_took_place_on_or_within ?place_uri . FILTER contains(str(?place_uri), "geonames")
                ?place_uri  geonames:countryCode ?place_country_code . }



       optional{ ?prod ecrm:P126_employed ?x .
                 ?material_group skos:member ?x FILTER contains(str(?material_group), "facet")}
      

      optional{ ?prod ecrm:P4_has_time-span ?time_uri .
                ?time_uri ecrm:P86_falls_within ?time_label . FILTER  (lang(?time_label) = 'en')}
       

       optional{ ?prod ecrm:P32_used_general_technique  ?y .
                ?technique_group skos:member ?y FILTER contains(str(?technique_group), "facet")
               }

       optional{ ?obj ecrm:P65_shows_visual_item  ?z .
                ?depict_group skos:member ?z FILTER contains(str(?depict_group), "facet")
               }

optional {?dig ecrm:P129_is_about ?type_a .
          ?type_a ecrm:P42_assigned ?P42 .
          ?type_a_group skos:member ?P42 FILTER contains(str(?type_a_group), "facet")
               }


}
ORDER BY ?museum
