prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>  
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>

SELECT DISTINCT ?g ?id ?obj ?technique ?depiction ?material ?timespan 
WHERE {
  GRAPH ?g {

     ?dig a crmdig:D1_Digital_Object . }
     ?dig  ecrm:P129_is_about ?img .

      ?dig ecrm:P129_is_about ?obj .
      ?obj a ecrm:E22_Man-Made_Object .
      ?dig ecrm:P129_is_about ?prd .
OPTIONAL { ?prd  ecrm:P4_has_time-span / ecrm:P78_is_identified_by ?timespan . }


OPTIONAL { ?obj ecrm:P62_depicts ?depiction . }
      
     ?obj  dc:identifier ?id .
   
OPTIONAL {
            { ?prd ecrm:P126_employed ?x
       { SELECT ?x SAMPLE(?lab) as ?material
         WHERE { ?x skos:prefLabel ?lab . FILTER (lang(?lab) = "en")}
       } . FILTER(isIRI(?x)) }
       UNION
       { ?prd ecrm:P126_employed ?material .
       FILTER (isIRI(?material) = false)
       FILTER (lang(?material) = "en")}
}     


OPTIONAL {
         { ?prd ecrm:P32_used_general_technique ?x
       { SELECT ?x SAMPLE(?lab) as ?technique
         WHERE { ?x skos:prefLabel ?lab . FILTER (lang(?lab) = "en")}
       } . FILTER(isIRI(?x)) }
       UNION
       { ?prd ecrm:P32_used_general_technique ?technique .
        FILTER (isIRI(?technique) = false)
        FILTER (lang(?technique) = "en")}
}


}

