SELECT distinct  ?title ?collection ?object ?location
WHERE { graph ?collection {
      ?s a ecrm:E12_Production .
      ?s ecrm:P108_has_produced ?object.
   optional {   ?obj ecrm:P3_has_note ?title . }

 { ?s ecrm:P8_took_place_on_or_within ?location
     { SELECT ?location SAMPLE(?loc) as ?place
          WHERE { ?location geonames:countryCode ?loc}
       } . FILTER(isIRI(?location))
           ?location geonames:countryCode "ES"  }


}}
