SELECT distinct count(distinct ?obj) as ?count  ?material
WHERE {

     ?dig a crmdig:D1_Digital_Object .
     ?dig  ecrm:P129_is_about ?prd .
     ?prd ecrm:P108_has_produced ?obj .
 
{ ?prd ecrm:P126_employed ?x
       { SELECT ?x SAMPLE(?lab) as ?material
         WHERE { ?x skos:prefLabel ?lab . }
       } . FILTER(isIRI(?x)) }
       UNION
       { ?prd ecrm:P126_employed ?material .
       FILTER (isIRI(?material) = false)
      }

{ ?prd ecrm:P8_took_place_on_or_within ?l
     { SELECT ?l SAMPLE(?loc) as ?place
          WHERE { ?l geonames:countryCode ?loc}
       } . FILTER(isIRI(?l))
           ?l geonames:countryCode "FR" }

?prd ecrm:P4_has_time-span ?t .
?t ecrm:P78_is_identified_by ?time.


FILTER contains(str(?time), "18")
}
GROUP BY ?material
ORDER BY DESC (?count)
