SELECT distinct  ?title ?description group_concat(distinct ?material;separator="|") as ?materials ?collection  ?object
WHERE { graph ?collection {

     ?dig a crmdig:D1_Digital_Object .
      
     ?dig  ecrm:P129_is_about ?prd .
     ?prd ecrm:P108_has_produced ?object .
 
     optional {?object ecrm:P102_has_title ?title }
     optional {?object ecrm:P3_has_note ?description }

        ?prd ecrm:P126_employed ?material  .



     MINUS {?prd ecrm:P126_employed <http://data.silknow.org/vocabulary/627> .}


        {?prd ecrm:P126_employed <http://data.silknow.org/vocabulary/644> .}
        UNION
        {?prd ecrm:P126_employed <http://data.silknow.org/vocabulary/628> .}

?prd ecrm:P4_has_time-span ?t .
?t ecrm:P78_is_identified_by ?time.


FILTER contains(str(?time), "17")

     
}}
GROUP BY ?object ?collection ?description  ?title
