SELECT distinct ?maker 
WHERE {

     ?dig a crmdig:D1_Digital_Object.
     ?dig ecrm:P129_is_about ?prd .

     ?prd ecrm:P9_consists_of ?activity .
     ?activity ecrm:P14_carried_out_by ?maker.
    
FILTER (contains(str(?maker), "Mariano") || contains(str(?maker), "Fortuny") ) 
     
}



