SELECT distinct  ?title group_concat(distinct ?material;separator="|") as ?materials ?time ?collection  ?object
WHERE { graph ?collection {

     ?dig a crmdig:D1_Digital_Object .
      
     ?dig  ecrm:P129_is_about ?prd .
     ?prd ecrm:P108_has_produced ?object .
 
     optional {?object ecrm:P102_has_title ?title }
     optional {?object ecrm:P3_has_note ?description }

        ?prd ecrm:P126_employed ?material  .



     MINUS {?prd ecrm:P126_employed <http://data.silknow.org/vocabulary/627> .}


        {?prd ecrm:P126_employed <http://data.silknow.org/vocabulary/644> .}
        UNION
        {?prd ecrm:P126_employed <http://data.silknow.org/vocabulary/628> .}
     
         { ?prd ecrm:P126_employed ?x
       { SELECT ?x SAMPLE(?lab) as ?material
         WHERE { ?x skos:prefLabel ?lab . FILTER (lang(?lab) = "en")}
       } . FILTER(isIRI(?x)) }
     UNION
     { ?prd ecrm:P126_employed ?material .
       FILTER (isIRI(?material) = false)
      }

?prd ecrm:P4_has_time-span ?t .
?t ecrm:P78_is_identified_by ?time.


FILTER (contains(str(?time), "17th") || contains(str(?time), "1600s") || contains(str(?time), "segle 17") || contains(str(?time), "1650s"))
     
}}
GROUP BY ?collection ?object  ?title ?time
