SELECT distinct ?time ?title ?description ?collection ?object 
WHERE { graph ?collection{

     ?dig a crmdig:D1_Digital_Object .
     ?dig  ecrm:P129_is_about ?prod .
     ?prod ecrm:P108_has_produced ?object .
 
 optional {?object ecrm:P102_has_title ?title }
     optional {?object ecrm:P3_has_note ?description }

?prod ecrm:P4_has_time-span ?t .
?t ecrm:P78_is_identified_by ?time.

{?t ecrm:P78_is_identified_by ?time .FILTER contains(str(?time), "16")}
         UNION
        {?prod ecrm:P4_has_time-span <http://vocab.getty.edu/aat/300404510> }
     
     
}}
