SELECT distinct ?time ?title ?description ?collection ?object ?start ?end
WHERE { graph ?collection{
     ?prod ecrm:P108_has_produced ?object .
 
     optional {?object ecrm:P102_has_title ?title }
     optional {?object ecrm:P3_has_note ?description }

     ?prod ecrm:P4_has_time-span ?ts .
     ?ts rdfs:label ?time.

     ?ts time:hasEnd / time:inXSDDate ?end ;
                time:hasBeginning / time:inXSDDate ?start .
     
     FILTER ( ?start <= "1815"^^xsd:gYear AND ?end >= "1815"^^xsd:gYear  )
}} ORDER BY (abs(year(?start) - 1815))
