prefix crmdig: <http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/>
prefix crmsci: <http://www.ics.forth.gr/isl/CRMsci/>
SELECT DISTINCT ?object ?title ?collection ?visual_item
WHERE {graph ?collection {



         optional {?object ecrm:P102_has_title ?title }
    ?object a ecrm:E22_Man-Made_Object .
    ?production ecrm:P108_has_produced ?object .

    
    
    { values ?vitem { <http://data.silknow.org/vocabulary/743> }
      ?object ecrm:P65_shows_visual_item ?vitem .
     ?vitem  skos:prefLabel ?visual_item FILTER(lang(str(?visual_item)) = "en")}
    

}}

