package org.silknow.converter.ontologies;/* CVS $Id: $ */

import org.apache.jena.ontology.OntClass;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.ontology.OntModelSpec;
import org.apache.jena.ontology.OntProperty;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from https://www.ics.forth.gr/isl/CRMext/CRMdig_v3.2.2.rdfs
 *
 * @author Auto-generated by schemagen on 08 gen 2019 18:23
 */
public class CRMdig {
  /**
   * <p>The ontology model that holds the vocabulary terms</p>
   */
  private static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

  /**
   * <p>The namespace of the vocabulary as a string</p>
   */
  public static final String NS = "http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/";

  /**
   * <p>The namespace of the vocabulary as a string</p>
   *
   * @see #NS
   */
  public static String getURI() {
    return NS;
  }

  /**
   * <p>The namespace of the vocabulary as a resource</p>
   */
  public static final Resource NAMESPACE = m_model.createResource(NS);

  public static final OntProperty L10_had_input = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L10_had_input");

  public static final OntProperty L10i_was_input_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L10i_was_input_of");

  public static final OntProperty L11_had_output = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L11_had_output");

  public static final OntProperty L11i_was_output_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L11i_was_output_of");

  public static final OntProperty L12_happened_on_device = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L12_happened_on_device");

  public static final OntProperty L12i_was_device_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L12i_was_device_for");

  public static final OntProperty L13_used_parameters = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L13_used_parameters");

  public static final OntProperty L13i_parameters_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L13i_parameters_for");

  public static final OntProperty L14_transferred = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L14_transferred");

  public static final OntProperty L14i_was_transferred_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L14i_was_transferred_by");

  public static final OntProperty L15_has_sender = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L15_has_sender");

  public static final OntProperty L15i_was_sender_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L15i_was_sender_for");

  public static final OntProperty L16_has_receiver = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L16_has_receiver");

  public static final OntProperty L16i_was_receiver_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L16i_was_receiver_for");

  public static final OntProperty L17_measured_thing_of_type = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L17_measured_thing_of_type");

  public static final OntProperty L17i_was_type_of_thing_measured_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L17i_was_type_of_thing_measured_by");

  public static final OntProperty L18_has_modified = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L18_has_modified");

  public static final OntProperty L18i_was_modified_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L18i_was_modified_by");

  public static final OntProperty L19_stores = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L19_stores");

  public static final OntProperty L19i_is_stored_on = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L19i_is_stored_on");

  public static final OntProperty L1_digitized = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L1_digitized");

  public static final OntProperty L1i_was_digitized_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L1i_was_digitized_by");

  public static final OntProperty L20_has_created = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L20_has_created");

  public static final OntProperty L20i_was_created_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L20i_was_created_by");

  public static final OntProperty L21_used_as_derivation_source = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L21_used_as_derivation_source");

  public static final OntProperty L21i_was_derivation_source_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L21i_was_derivation_source_for");

  public static final OntProperty L22_created_derivative = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L22_created_derivative");

  public static final OntProperty L22i_was_derivative_created_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L22i_was_derivative_created_by");

  public static final OntProperty L23_used_software_or_firmware = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L23_used_software_or_firmware");

  public static final OntProperty L23i_was_software_or_firmware_used_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L23i_was_software_or_firmware_used_by");

  public static final OntProperty L24_created_logfile = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L24_created_logfile");

  public static final OntProperty L24i_was_logfile_created_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L24i_was_logfile_created_by");

  public static final OntProperty L29_has_responsible_organization = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L29_has_responsible_organization");

  public static final OntProperty L29i_is_responsible_organization_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L29i_is_responsible_organization_for");

  public static final OntProperty L2_used_as_source = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L2_used_as_source");

  public static final OntProperty L2i_was_source_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L2i_was_source_for");

  public static final OntProperty L30_has_operator = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L30_has_operator");

  public static final OntProperty L30i_is_operator_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L30i_is_operator_of");

  public static final OntProperty L31_has_starting_date_time = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L31_has_starting_date-time");

  public static final OntProperty L32_has_ending_date_time = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L32_has_ending_date-time");

  public static final OntProperty L33_has_maker = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L33_has_maker");

  public static final OntProperty L33i_is_maker_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L33i_is_maker_of");

  public static final OntProperty L34_has_contractor = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L34_has_contractor");

  public static final OntProperty L34i_is_contractor_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L34i_is_contractor_for");

  public static final OntProperty L35_has_commissioner = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L35_has_commissioner");

  public static final OntProperty L35i_is_commissioner_for = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L35i_is_commissioner_for");

  public static final OntProperty L43_annotates = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L43_annotates");

  public static final OntProperty L43i_is_annotated_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L43i_is_annotated_by");

  public static final OntProperty L47_has_comment = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L47_has_comment");

  public static final OntProperty L48_created_annotation = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L48_created_annotation");

  public static final OntProperty L48i_was_annotation_created_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L48i_was_annotation_created_by");

  public static final OntProperty L49_is_primary_area_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L49_is_primary_area_of");

  public static final OntProperty L49i_has_primary_area = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L49i_has_primary_area");

  public static final OntProperty L4_has_preferred_label = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L4_has_preferred_label");

  public static final OntProperty L50_is_propagated_area_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L50_is_propagated_area_of");

  public static final OntProperty L50i_has_propagated_area = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L50i_has_propagated_area");

  public static final OntProperty L51_has_first_name = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L51_has_first_name");

  public static final OntProperty L52_has_last_name = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L52_has_last_name");

  public static final OntProperty L53_is_not_uniquely_identified_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L53_is_not_uniquely_identified_by");

  public static final OntProperty L54_is_same_as = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L54_is_same-as");

  public static final OntProperty L54i_is_same_as = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L54i_is_same-as");

  public static final OntProperty L55_has_inventory_no = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L55_has_inventory_no");

  public static final OntProperty L56_has_pixel_width = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L56_has_pixel_width");

  public static final OntProperty L57_has_pixel_height = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L57_has_pixel_height");

  public static final OntProperty L59_has_serial_number = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L59_has_serial_number");

  public static final OntProperty L60_documents = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L60_documents");

  public static final OntProperty L60i_is_documented_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L60i_is_documented_by");

  public static final OntProperty L61_was_ongoing_at = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/L61_was_ongoing_at");

  public static final OntClass D10_Software_Execution = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D10_Software_Execution");

  public static final OntClass D11_Digital_Measurement_Event = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D11_Digital_Measurement_Event");

  public static final OntClass D12_Data_Transfer_Event = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D12_Data_Transfer_Event");

  public static final OntClass D13_Digital_Information_Carrier = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D13_Digital_Information_Carrier");

  public static final OntClass D14_Software = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D14_Software");

  public static final OntClass D1_Digital_Object = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D1_Digital_Object");

  public static final OntClass D21_Person_Name = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D21_Person_Name");

  public static final OntClass D23_Room = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D23_Room");

  public static final OntClass D29_Annotation_Object = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D29_Annotation_Object");

  public static final OntClass D2_Digitization_Process = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D2_Digitization_Process");

  public static final OntClass D30_Annotation_Event = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D30_Annotation_Event");

  public static final OntClass D35_Area = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D35_Area");

  public static final OntClass D3_Formal_Derivation = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D3_Formal_Derivation");

  public static final OntClass D7_Digital_Machine_Event = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D7_Digital_Machine_Event");

  public static final OntClass D8_Digital_Device = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D8_Digital_Device");

  public static final OntClass D9_Data_Object = m_model.createClass("http://www.ics.forth.gr/isl/CRMext/CRMdig.rdfs/D9_Data_Object");

}