/* CVS $Id: $ */
package org.silknow.converter.ontologies;

import org.apache.jena.ontology.OntClass;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.ontology.OntModelSpec;
import org.apache.jena.ontology.OntProperty;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from https://www.ics.forth.gr/isl/CRMext/CRMsci_v1.2.3.rdfs
 *
 * @author Auto-generated by schemagen on 10 gen 2019 14:29
 */
public class CRMsci {
  /**
   * <p>The ontology model that holds the vocabulary terms</p>
   */
  private static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

  /**
   * <p>The namespace of the vocabulary as a string</p>
   */
  public static final String NS = "http://www.ics.forth.gr/isl/CRMsci/";

  /**
   * <p>The namespace of the vocabulary as a string</p>
   *
   * @see #NS
   */
  public static String getURI() {
    return NS;
  }

  /**
   * <p>The namespace of the vocabulary as a resource</p>
   */
  public static final Resource NAMESPACE = m_model.createResource(NS);

  public static final OntProperty O10_assigned_dimension = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O10_assigned_dimension");

  public static final OntProperty O10i_dimension_was_assigned_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O10i_dimension_was_assigned_by");

  public static final OntProperty O11_described = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O11_described");

  public static final OntProperty O11i_was_described_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O11i_was_described_by");

  public static final OntProperty O12_has_dimension = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O12_has_dimension");

  public static final OntProperty O12i_is_dimension_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O12i_is_dimension_of");

  public static final OntProperty O13_triggers = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O13_triggers");

  public static final OntProperty O13i_is_triggered_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O13i_is_triggered_by");

  public static final OntProperty O14_initializes = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O14_initializes");

  public static final OntProperty O14i_is_initialized_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O14i_is_initialized_by");

  public static final OntProperty O15_occupied = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O15_occupied");

  public static final OntProperty O15i_was_occupied_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O15i_was_occupied_by");

  public static final OntProperty O16_observed_value = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O16_observed_value");

  public static final OntProperty O16i_value_was_observed_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O16i_value_was_observed_by");

  public static final OntProperty O17_generated = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O17_generated");

  public static final OntProperty O17i_was_generated_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O17i_was_generated_by");

  public static final OntProperty O18_altered = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O18_altered");

  public static final OntProperty O18i_was_altered_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O18i_was_altered_by");

  public static final OntProperty O19_has_found_object = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O19_has_found_object");

  public static final OntProperty O19i_was_object_found_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O19i_was_object_found_by");

  public static final OntProperty O1_diminished = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O1_diminished");

  public static final OntProperty O1i_was_diminished_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O1i_was_diminished_by");

  public static final OntProperty O20_sampled_from_type_of_part = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O20_sampled_from_type_of_part");

  public static final OntProperty O20i_type_of_part_was_sampled_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O20i_type_of_part_was_sampled_by");

  public static final OntProperty O21_has_found_at = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O21_has_found_at");

  public static final OntProperty O21i_witnessed = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O21i_witnessed");

  public static final OntProperty O22_partly_or_completely_contains = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O22_partly_or_completely_contains");

  public static final OntProperty O22i_is_part_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O22i_is_part_of");

  public static final OntProperty O23_is_defined_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O23_is_defined_by");

  public static final OntProperty O23i_defines = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O23i_defines");

  public static final OntProperty O24_measured = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O24_measured");

  public static final OntProperty O24i_was_measured_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O24i_was_measured_by");

  public static final OntProperty O2_removed = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O2_removed");

  public static final OntProperty O2i_was_removed_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O2i_was_removed_by");

  public static final OntProperty O3_sampled_from = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O3_sampled_from");

  public static final OntProperty O3i_was_sample_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O3i_was_sample_by");

  public static final OntProperty O4_sampled_at = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O4_sampled_at");

  public static final OntProperty O4i_was_sampling_location_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O4i_was_sampling_location_of");

  public static final OntProperty O5_removed = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O5_removed");

  public static final OntProperty O5i_was_removed_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O5i_was_removed_by");

  public static final OntProperty O6_forms_former_or_current_part_of = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O6_forms_former_or_current_part_of");

  public static final OntProperty O6i_has_former_or_current_part = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O6i_has_former_or_current_part");

  public static final OntProperty O7_contains_or_confines = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O7_contains_or_confines");

  public static final OntProperty O7i_is_contained_or_confined = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O7i_is_contained_or_confined");

  public static final OntProperty O8_observed = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O8_observed");

  public static final OntProperty O8i_was_observed_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O8i_was_observed_by");

  public static final OntProperty O9_observed_property_type = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O9_observed_property_type");

  public static final OntProperty O9i_property_type_was_observed_by = m_model.createOntProperty("http://www.ics.forth.gr/isl/CRMsci/O9i_property_type_was_observed_by");

  public static final OntClass S10_Material_Substantial = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S10_Material_Substantial");

  public static final OntClass S11_Amount_of_Matter = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S11_Amount_of_Matter");

  public static final OntClass S12_Amount_of_Fluid = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S12_Amount_of_Fluid");

  public static final OntClass S13_Sample = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S13_Sample");

  public static final OntClass S14_Fluid_Body = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S14_Fluid_Body");

  public static final OntClass S15_Observable_Entity = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S15_Observable_Entity");

  public static final OntClass S16_State = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S16_State");

  public static final OntClass S17_Physical_Genesis = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S17_Physical_Genesis");

  public static final OntClass S18_Alteration = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S18_Alteration");

  public static final OntClass S19_Encounter_Event = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S19_Encounter_Event");

  public static final OntClass S1_Matter_Removal = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S1_Matter_Removal");

  public static final OntClass S20_Physical_Feature = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S20_Physical_Feature");

  public static final OntClass S21_Measurement = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S21_Measurement");

  public static final OntClass S22_Segment_of_Matter = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S22_Segment_of_Matter");

  public static final OntClass S2_Sample_Taking = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S2_Sample_Taking");

  public static final OntClass S3_Measurement_by_Sampling = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S3_Measurement_by_Sampling");

  public static final OntClass S4_Observation = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S4_Observation");

  public static final OntClass S5_Inference_Making = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S5_Inference_Making");

  public static final OntClass S6_Data_Evaluation = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S6_Data_Evaluation");

  public static final OntClass S7_Simulation_or_Prediction = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S7_Simulation_or_Prediction");

  public static final OntClass S8_Categorical_Hypothesis_Building = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S8_Categorical_Hypothesis_Building");

  public static final OntClass S9_Property_Type = m_model.createClass("http://www.ics.forth.gr/isl/CRMsci/S9_Property_Type");

}
